### ISSUE TITLE
visualized grid lines are mispositioned, if grid has a border

### ISSUE THREAD

**Issue by dholbert** [potch/gridviz#2]
STR:
 1. Load http://people.mozilla.org/~dholbert/tests/grid-lines-tests/border1.html
  (which I've attached here for archival purposes, too: [border1.zip](https://github.com/potch/gridviz/files/221914/border1.zip))
 2. Activate gridviz by clicking its toolbar button.

ACTUAL RESULTS:
Lines are to the upper-left of where they should actually be -- they don't actually match the actual grid areas. It seems gridviz isn't considering the grid's border when computing where the grid lines should appear onscreen.

**Comment by dholbert** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/426803/14576733/dd88b768-0320-11e6-94c3-54b335c68e81.png)

**Comment by potch** [comment]
Fixed by efbdf698b:

<img width="370" alt="screenshot 2016-04-22 14 15 53" src="https://cloud.githubusercontent.com/assets/253470/14755122/ca82d116-0894-11e6-8772-4958bd0a058f.png">
